// Defines RTK Query endpoints for fetching data from the server.
// Each endpoint configures URL, method, and query parameters as needed.

import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

export const api = createApi({
  // Base URL from environment variable
  baseQuery: fetchBaseQuery({
    baseUrl: process.env.REACT_APP_BASE_URL,
  }),

  // Unique name for the reducer path in Redux store
  reducerPath: "adminApi",

  // Tags for invalidation/refresh
  tagTypes: [
    "User",
    "Products",
    "Customers",
    "Transactions",
    "Geography",
    "Sales",
    "Admins",
    "Performance",
    "Dashboard",
  ],

  endpoints: (build) => ({
    // Fetch single user by ID
    getUser: build.query({
      query: (id) => `general/user/${id}`,
      providesTags: ["User"],
    }),

    // Fetch all products
    getProducts: build.query({
      query: () => "client/products",
      providesTags: ["Products"],
    }),

    // Fetch all customers with role "user"
    getCustomers: build.query({
      query: () => "client/customers",
      providesTags: ["Customers"],
    }),

    // Fetch paginated, sorted, searched transactions
    getTransactions: build.query({
      query: ({ page, pageSize, sort, search }) => ({
        url: "client/transactions",
        method: "GET",
        // Pass query params for pagination, sorting, and search
        params: { page, pageSize, sort, search },
      }),
      providesTags: ["Transactions"],
    }),

    // Fetch user distribution by country
    getGeography: build.query({
      query: () => "client/geography",
      providesTags: ["Geography"],
    }),

    // Fetch overall sales data (daily, monthly, etc.)
    getSales: build.query({
      query: () => "sales/sales",
      providesTags: ["Sales"],
    }),

    // Fetch admin user list
    getAdmins: build.query({
      query: () => "management/admins",
      providesTags: ["Admins"],
    }),

    // Fetch affiliate performance data for a user
    getUserPerformance: build.query({
      query: (id) => `management/performance/${id}`,
      providesTags: ["Performance"],
    }),

    // Fetch dashboard data (stats, charts)
    getDashboard: build.query({
      query: () => "general/dashboard",
      providesTags: ["Dashboard"],
    }),
  }),
});

// Export hooks generated by RTK Query
export const {
  useGetUserQuery,
  useGetProductsQuery,
  useGetCustomersQuery,
  useGetTransactionsQuery,
  useGetGeographyQuery,
  useGetSalesQuery,
  useGetAdminsQuery,
  useGetUserPerformanceQuery,
  useGetDashboardQuery,
} = api;